INSERT INTO [dbo].[Table_Data]
           ([Id]
           ,[Label]
           ,[TextBox]
           ,[Button]
           ,[LinkButton]
           ,[CheckBox]
           ,[RadioButton])
     VALUES
           (1
           ,'La1'
           ,'T1'
           ,'B1'
           ,'L1'
           ,'True'
           ,'False'),
		   (2
           ,'La2'
           ,'T2'
           ,'B2'
           ,'L2'
           ,'False'
           ,'True'),
		   (3
           ,'La3'
           ,'T3'
           ,'B3'
           ,'L3'
           ,'True'
           ,'False')